### PR TITLE
Add model object get and select shortcuts, and get and set uda

### PR DESCRIPTION
**Pull request by JarlAlexLupu**

### CODE REVIEW

**Comment by CarlosHerrero** [comment]
Hello,

There seems to be a problem with lambda expressions. Missing ref?

**Comment by JarlAlexLupu** [comment]
Hi, 

I've used VS2017, Removed the fat arrows.

**Comment by CarlosHerrero** [comment]
OK, please, take into account that changes in this repo are not moved to the .dll distributed with TS. That .dll is built using code stored in the internal git servers. But anyone can take this repository, add code or modify existing one, change name and distribute it with own tools.

**Comment by JarlAlexLupu** [comment]
No problem, if you think it should go there also, feel free to copy it there

**Pull request closed without merging**
